# Generated by Django 5.0.2 on 2024-02-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Малюнок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('likes', models.IntegerField(default=0, verbose_name='Вподобайки')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Невподобайки')),
                ('views', models.IntegerField(default=0, verbose_name='Перегляди')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
        ),
    ]
